export let quotes = [{text: "The greatest glory in living lies not in never falling, but in rising every time we fall.", author: "Nelson Mandela"},
              {text: "The way to get started is to quit talking and begin doing.", author: "Walt Disney"},
              {text: "Your time is limited, so don't waste it living someone else's life. Don't be trapped by dogma – which is living with the results of other people's thinking.", author: "Steve Jobs"},
              {text: "If life were predictable it would cease to be life, and be without flavor.", author: "Eleanor Roosevelt"},
              {text: "If you look at what you have in life, you'll always have more. If you look at what you don't have in life, you'll never have enough.", author: "Oprah Winfrey"},
              {text: "If you set your goals ridiculously high and it's a failure, you will fail above everyone else's success.", author: "James Cameron"},
              {text: "When you reach the end of your rope, tie a knot in it and hang on.", author: "Franklin D. Roosevelt"},
              {text: "In the end, it's not the years in your life that count. It's the life in your years.", author: "Abraham Lincoln"},
              {text: "Be yourself; everyone else is already taken.", author: "Oscar Wilde"},
              {text: "A fashion is nothing but an induced epidemic.", author: "George Bernard Shaw"},
              {text: "Progress is impossible without change, and those who cannot change their minds cannot change anything.", author: "George Bernard Shaw"},
              {text: "Live as if you were to die tomorrow. Learn as if you were to live forever.", author: "Mahatma Gandhi"},
              {text: "We must not allow other people’s limited perceptions to define us.", author: "Virginia Satir"},
              {text: "If you cannot do great things, do small things in a great way.", author: "Napoleon Hill"},
              {text: "Wise men speak because they have something to say; fools because they have to say something.", author: "Plato"},
              {text: "I want to feel what I feel. What's mine. Even if it's not happiness, whatever that means. Because you're all you've got.", author: "Toni Morrison"},
              {text: "I think we are well-advised to keep on nodding terms with the people we used to be, whether we find them attractive company or not. Otherwise they turn up unannounced and surprise us...", author: "Joan Didion"},
              {text: "When the going gets weird, the weird turn pro.", author: "Hunter S. Thompson"},
              {text: "The world breaks everyone, and afterward, some are strong at the broken places.", author: "Ernest Hemingway"},
              {text: "In a murderous time the heart breaks and breaks and lives by breaking.", author: "Stanley Kunitz"}
      ]
